export type ItemRecord = {
  id: string
  name: string
  category: 'weapon' | 'armor' | 'shield' | 'tool' | 'gear' | 'ammunition'
  subcategory: string
  cost_gp: number
  weight_lb: number
  description: string
  damage: string | null
  damage_type: string | null
  properties: string[]
  ac_base: number | null
  dex_mod: boolean
  max_dex: number | null
  str_req: number | null
  stealth_disadvantage: boolean
  equipped: boolean
  quantity: number
  notes: string
}

export const ITEM_CATALOG: Record<string, ItemRecord> = {
  dagger: {
    id: 'dagger',
    name: 'Dagger',
    category: 'weapon',
    subcategory: 'simple',
    cost_gp: 2,
    weight_lb: 1,
    description: '',
    damage: '1d4',
    damage_type: 'piercing',
    properties: ['Finesse', 'Light', 'Thrown (20/60)'],
    ac_base: null,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  longsword: {
    id: 'longsword',
    name: 'Longsword',
    category: 'weapon',
    subcategory: 'martial',
    cost_gp: 15,
    weight_lb: 3,
    description: '',
    damage: '1d8',
    damage_type: 'slashing',
    properties: ['Versatile (1d10)'],
    ac_base: null,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  shortbow: {
    id: 'shortbow',
    name: 'Shortbow',
    category: 'weapon',
    subcategory: 'simple',
    cost_gp: 25,
    weight_lb: 2,
    description: '',
    damage: '1d6',
    damage_type: 'piercing',
    properties: ['Ammunition (80/320)', 'Two-Handed'],
    ac_base: null,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    category: 'armor',
    subcategory: 'light',
    cost_gp: 10,
    weight_lb: 10,
    description: '',
    damage: null,
    damage_type: null,
    properties: [],
    ac_base: 11,
    dex_mod: true,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  chain_mail: {
    id: 'chain_mail',
    name: 'Chain Mail',
    category: 'armor',
    subcategory: 'heavy',
    cost_gp: 75,
    weight_lb: 55,
    description: '',
    damage: null,
    damage_type: null,
    properties: [],
    ac_base: 16,
    dex_mod: false,
    max_dex: null,
    str_req: 13,
    stealth_disadvantage: true,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  shield: {
    id: 'shield',
    name: 'Shield',
    category: 'shield',
    subcategory: 'shield',
    cost_gp: 10,
    weight_lb: 6,
    description: '+2 AC. Requires one free hand.',
    damage: null,
    damage_type: null,
    properties: [],
    ac_base: 2,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  thieves_tools: {
    id: 'thieves_tools',
    name: "Thieves' Tools",
    category: 'tool',
    subcategory: 'specialist',
    cost_gp: 25,
    weight_lb: 1,
    description: 'Pick locks and disarm traps.',
    damage: null,
    damage_type: null,
    properties: [],
    ac_base: null,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  explorer_pack: {
    id: 'explorer_pack',
    name: "Explorer's Pack",
    category: 'gear',
    subcategory: 'adventuring',
    cost_gp: 10,
    weight_lb: 59,
    description: 'Backpack, bedroll, mess kit, tinderbox, torches, rations, waterskin, and rope.',
    damage: null,
    damage_type: null,
    properties: [],
    ac_base: null,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
  arrows_20: {
    id: 'arrows_20',
    name: 'Arrows (20)',
    category: 'ammunition',
    subcategory: 'ammunition',
    cost_gp: 1,
    weight_lb: 1,
    description: '',
    damage: null,
    damage_type: null,
    properties: [],
    ac_base: null,
    dex_mod: false,
    max_dex: null,
    str_req: null,
    stealth_disadvantage: false,
    equipped: false,
    quantity: 1,
    notes: '',
  },
}
